# Generated by Django 2.1.1 on 2019-09-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('instit', models.TextField()),
                ('img', models.ImageField(upload_to='uploaded_imgs')),
                ('designation', models.BooleanField(default=False)),
            ],
        ),
    ]
